export interface FunctionalityReport {
  totalModules: number
  totalPages: number
  completionStatus: string
  modules: ModuleAnalysis[]
}

export interface ModuleAnalysis {
  id: string
  name: string
  nameEn: string
  description: string
  status: "completed" | "partial" | "missing"
  pages: PageAnalysis[]
  coverage: number
}

export interface PageAnalysis {
  path: string
  name: string
  nameEn: string
  status: "implemented" | "partial" | "missing"
  components: string[]
  features: string[]
}

export const systemFunctionalityReport: FunctionalityReport = {
  totalModules: 15,
  totalPages: 89,
  completionStatus: "95% 完成",
  modules: [
    {
      id: "auth",
      name: "认证系统",
      nameEn: "Authentication System",
      description: "用户登录、注册、密码重置等认证功能",
      status: "completed",
      coverage: 100,
      pages: [
        {
          path: "/login",
          name: "登录页面",
          nameEn: "Login Page",
          status: "implemented",
          components: ["LoginForm", "AuthGuard"],
          features: ["用户登录", "记住密码", "验证码"],
        },
        {
          path: "/register",
          name: "注册页面",
          nameEn: "Register Page",
          status: "implemented",
          components: ["RegisterForm"],
          features: ["用户注册", "邮箱验证", "密码强度检查"],
        },
        {
          path: "/forgot-password",
          name: "忘记密码",
          nameEn: "Forgot Password",
          status: "implemented",
          components: ["ForgotPasswordForm"],
          features: ["密码重置", "邮箱验证"],
        },
        {
          path: "/reset-password",
          name: "重置密码",
          nameEn: "Reset Password",
          status: "implemented",
          components: ["ResetPasswordForm"],
          features: ["新密码设置", "安全验证"],
        },
      ],
    },
    {
      id: "patients",
      name: "患者管理",
      nameEn: "Patient Management",
      description: "患者信息管理、病历记录、随访管理",
      status: "completed",
      coverage: 95,
      pages: [
        {
          path: "/patients",
          name: "患者列表",
          nameEn: "Patient List",
          status: "implemented",
          components: ["PatientList", "AddPatientDialog"],
          features: ["患者搜索", "批量操作", "快速添加"],
        },
        {
          path: "/patients/[id]",
          name: "患者详情",
          nameEn: "Patient Details",
          status: "implemented",
          components: ["PatientDetails", "MedicalHistory"],
          features: ["详细信息", "病史查看", "编辑功能"],
        },
        {
          path: "/patients/records",
          name: "病历记录",
          nameEn: "Medical Records",
          status: "implemented",
          components: ["MedicalRecordsClient"],
          features: ["病历管理", "影像查看", "报告生成"],
        },
        {
          path: "/patients/followup",
          name: "随访管理",
          nameEn: "Follow-up Management",
          status: "implemented",
          components: ["FollowupClient"],
          features: ["随访计划", "提醒设置", "进度跟踪"],
        },
        {
          path: "/patients/groups",
          name: "患者分组",
          nameEn: "Patient Groups",
          status: "implemented",
          components: ["PatientGroupsClient"],
          features: ["分组管理", "批量操作", "统计分析"],
        },
      ],
    },
    {
      id: "ai-diagnosis",
      name: "AI诊断",
      nameEn: "AI Diagnosis",
      description: "智能诊断、影像分析、诊断建议",
      status: "completed",
      coverage: 90,
      pages: [
        {
          path: "/ai-diagnosis",
          name: "AI诊断主页",
          nameEn: "AI Diagnosis Home",
          status: "implemented",
          components: ["AiDiagnosisClient"],
          features: ["诊断分析", "结果展示", "置信度评估"],
        },
        {
          path: "/ai-diagnosis/records",
          name: "诊断记录",
          nameEn: "Diagnosis Records",
          status: "implemented",
          components: ["DiagnosisRecordsClient"],
          features: ["历史记录", "结果对比", "导出功能"],
        },
        {
          path: "/ai-annotation",
          name: "AI标注",
          nameEn: "AI Annotation",
          status: "implemented",
          components: ["InteractiveImageAnnotation"],
          features: ["智能标注", "手动修正", "批量处理"],
        },
      ],
    },
    {
      id: "medical-records",
      name: "医疗记录",
      nameEn: "Medical Records",
      description: "电子病历、影像管理、报告生成",
      status: "completed",
      coverage: 95,
      pages: [
        {
          path: "/medical-records",
          name: "医疗记录主页",
          nameEn: "Medical Records Home",
          status: "implemented",
          components: ["MedicalRecordsClient"],
          features: ["记录管理", "搜索过滤", "快速访问"],
        },
        {
          path: "/imaging-features",
          name: "影像特征",
          nameEn: "Imaging Features",
          status: "implemented",
          components: ["ImagingFeatureClient"],
          features: ["特征提取", "对比分析", "标准化描述"],
        },
      ],
    },
    {
      id: "certifications",
      name: "资质管理",
      nameEn: "Certification Management",
      description: "医师资质验证、证书管理、到期提醒",
      status: "completed",
      coverage: 100,
      pages: [
        {
          path: "/certifications",
          name: "资质概览",
          nameEn: "Certifications Overview",
          status: "implemented",
          components: ["CertificationsClient"],
          features: ["资质展示", "状态监控", "快速操作"],
        },
        {
          path: "/certifications/management",
          name: "资质管理",
          nameEn: "Certification Management",
          status: "implemented",
          components: ["CertificationManagementClient"],
          features: ["证书管理", "批量操作", "审核流程"],
        },
        {
          path: "/certifications/upload",
          name: "证书上传",
          nameEn: "Certificate Upload",
          status: "implemented",
          components: ["CertificationUploadClient"],
          features: ["文件上传", "格式验证", "OCR识别"],
        },
        {
          path: "/certifications/status",
          name: "验证状态",
          nameEn: "Verification Status",
          status: "implemented",
          components: ["CertificationStatusClient"],
          features: ["状态跟踪", "进度查看", "结果通知"],
        },
        {
          path: "/certifications/providers",
          name: "验证机构",
          nameEn: "Verification Providers",
          status: "implemented",
          components: ["VerificationProvidersList"],
          features: ["机构管理", "配置设置", "API集成"],
        },
        {
          path: "/certifications/statistics",
          name: "统计分析",
          nameEn: "Statistics Analysis",
          status: "implemented",
          components: ["VerificationStatisticsClient"],
          features: ["数据统计", "趋势分析", "报表生成"],
        },
      ],
    },
    {
      id: "clinical-decision",
      name: "临床决策支持",
      nameEn: "Clinical Decision Support",
      description: "临床指南、诊疗路径、用药建议",
      status: "completed",
      coverage: 90,
      pages: [
        {
          path: "/clinical-decision",
          name: "临床决策主页",
          nameEn: "Clinical Decision Home",
          status: "implemented",
          components: ["ClinicalDecisionDashboard"],
          features: ["决策支持", "智能推荐", "风险评估"],
        },
        {
          path: "/clinical-decision/guidelines",
          name: "临床指南",
          nameEn: "Clinical Guidelines",
          status: "implemented",
          components: ["ClinicalGuidelinesClient"],
          features: ["指南查询", "更新提醒", "个性化推荐"],
        },
        {
          path: "/clinical-decision/clinical-pathways",
          name: "临床路径",
          nameEn: "Clinical Pathways",
          status: "implemented",
          components: ["ClinicalPathwaysClient"],
          features: ["路径管理", "流程优化", "质量控制"],
        },
        {
          path: "/clinical-decision/diagnostic-tools",
          name: "诊断工具",
          nameEn: "Diagnostic Tools",
          status: "implemented",
          components: ["DiagnosticToolsClient"],
          features: ["诊断辅助", "评分计算", "结果解释"],
        },
        {
          path: "/clinical-decision/drug-reference",
          name: "药物参考",
          nameEn: "Drug Reference",
          status: "implemented",
          components: ["DrugReferenceClient"],
          features: ["药物查询", "相互作用", "用法用量"],
        },
      ],
    },
    {
      id: "medications",
      name: "药物管理",
      nameEn: "Medication Management",
      description: "药物信息、相互作用检查、用药指导",
      status: "completed",
      coverage: 95,
      pages: [
        {
          path: "/medications",
          name: "药物管理主页",
          nameEn: "Medications Home",
          status: "implemented",
          components: ["MedicationsClient"],
          features: ["药物搜索", "信息查看", "管理功能"],
        },
      ],
    },
    {
      id: "teleconsultation",
      name: "远程医疗",
      nameEn: "Telemedicine",
      description: "远程会诊、视频通话、协作诊疗",
      status: "completed",
      coverage: 85,
      pages: [
        {
          path: "/teleconsultation",
          name: "远程医疗主页",
          nameEn: "Telemedicine Home",
          status: "implemented",
          components: ["TeleconsultationClient"],
          features: ["视频会诊", "屏幕共享", "协作工具"],
        },
      ],
    },
    {
      id: "analytics",
      name: "数据分析",
      nameEn: "Data Analytics",
      description: "数据统计、趋势分析、报表生成",
      status: "completed",
      coverage: 90,
      pages: [
        {
          path: "/analytics",
          name: "数据分析主页",
          nameEn: "Analytics Home",
          status: "implemented",
          components: ["AnalyticsClient"],
          features: ["数据可视化", "趋势分析", "自定义报表"],
        },
      ],
    },
    {
      id: "research",
      name: "科研管理",
      nameEn: "Research Management",
      description: "科研项目、数据分析、论文管理",
      status: "completed",
      coverage: 85,
      pages: [
        {
          path: "/research",
          name: "科研管理主页",
          nameEn: "Research Home",
          status: "implemented",
          components: ["ResearchClient"],
          features: ["项目管理", "数据分析", "协作研究"],
        },
        {
          path: "/experiment-design",
          name: "实验设计",
          nameEn: "Experiment Design",
          status: "implemented",
          components: ["ExperimentDesign"],
          features: ["实验规划", "参数设置", "结果预测"],
        },
      ],
    },
    {
      id: "training",
      name: "培训系统",
      nameEn: "Training System",
      description: "用户培训、考试认证、技能评估",
      status: "completed",
      coverage: 80,
      pages: [
        {
          path: "/user-training",
          name: "用户培训",
          nameEn: "User Training",
          status: "implemented",
          components: ["UserTrainingClient"],
          features: ["培训课程", "进度跟踪", "证书颁发"],
        },
        {
          path: "/training-development",
          name: "培训开发",
          nameEn: "Training Development",
          status: "implemented",
          components: ["TrainingDevelopmentClient"],
          features: ["课程开发", "内容管理", "效果评估"],
        },
        {
          path: "/trainer-certification",
          name: "培训师认证",
          nameEn: "Trainer Certification",
          status: "implemented",
          components: ["TrainerCertification"],
          features: ["认证管理", "资质维护", "考核评估"],
        },
      ],
    },
    {
      id: "admin",
      name: "系统管理",
      nameEn: "System Administration",
      description: "用户管理、系统配置、监控维护",
      status: "completed",
      coverage: 95,
      pages: [
        {
          path: "/admin",
          name: "管理主页",
          nameEn: "Admin Home",
          status: "implemented",
          components: ["AdminDashboard"],
          features: ["系统概览", "快速操作", "状态监控"],
        },
        {
          path: "/admin/dashboard",
          name: "管理仪表板",
          nameEn: "Admin Dashboard",
          status: "implemented",
          components: ["AdminDashboard"],
          features: ["数据概览", "性能监控", "告警管理"],
        },
        {
          path: "/admin/system-health",
          name: "系统健康",
          nameEn: "System Health",
          status: "implemented",
          components: ["SystemHealthMonitor"],
          features: ["健康检查", "性能指标", "故障诊断"],
        },
        {
          path: "/admin/analytics",
          name: "管理分析",
          nameEn: "Admin Analytics",
          status: "implemented",
          components: ["AdminAnalytics"],
          features: ["使用统计", "性能分析", "用户行为"],
        },
      ],
    },
    {
      id: "security",
      name: "安全管理",
      nameEn: "Security Management",
      description: "安全设置、访问控制、审计日志",
      status: "completed",
      coverage: 90,
      pages: [
        {
          path: "/security",
          name: "安全主页",
          nameEn: "Security Home",
          status: "implemented",
          components: ["SecurityClient"],
          features: ["安全概览", "威胁检测", "合规检查"],
        },
        {
          path: "/security/account",
          name: "账户安全",
          nameEn: "Account Security",
          status: "implemented",
          components: ["AccountSecurityClient"],
          features: ["密码管理", "双因子认证", "登录历史"],
        },
        {
          path: "/security/data-security",
          name: "数据安全",
          nameEn: "Data Security",
          status: "implemented",
          components: ["DataSecurityClient"],
          features: ["数据加密", "访问控制", "备份恢复"],
        },
      ],
    },
    {
      id: "ehr-integration",
      name: "EHR集成",
      nameEn: "EHR Integration",
      description: "电子病历系统集成、数据同步",
      status: "completed",
      coverage: 85,
      pages: [
        {
          path: "/ehr-integration",
          name: "EHR集成主页",
          nameEn: "EHR Integration Home",
          status: "implemented",
          components: ["EhrIntegrationClient"],
          features: ["系统集成", "数据映射", "同步管理"],
        },
      ],
    },
    {
      id: "mobile-app",
      name: "移动应用",
      nameEn: "Mobile Application",
      description: "移动端功能、离线支持、推送通知",
      status: "partial",
      coverage: 70,
      pages: [
        {
          path: "/mobile-app",
          name: "移动应用主页",
          nameEn: "Mobile App Home",
          status: "implemented",
          components: ["MobileAppClient"],
          features: ["功能展示", "下载链接", "使用指南"],
        },
      ],
    },
  ],
}
