import {
  Activity,
  BarChart3,
  Brain,
  FileText,
  Home,
  Lock,
  Settings,
  Smartphone,
  Stethoscope,
  UserCog,
  Users,
  Video,
  Workflow,
  BookOpen,
  Microscope,
  Pill,
  HeartPulse,
  Clipboard,
  CalendarClock,
  ShieldCheck,
  Network,
  LineChart,
  BarChart,
  ArrowUpDown,
  Award,
  CheckCircle,
  FileCheck,
  UserCheck,
  BadgeIcon as Certificate,
  Key,
  HardDrive,
  AlertCircle,
  Bell,
  Globe,
  Code,
  Monitor,
  TestTube,
  History,
} from "lucide-react"

export const navItems = [
  {
    title: "系统主页",
    href: "/",
    icon: Home,
  },
  {
    title: "智能诊断",
    icon: Brain,
    children: [
      { title: "诊断中心", href: "/ai-diagnosis", icon: Stethoscope },
      { title: "模型管理", href: "/ai-model", icon: Brain },
      { title: "诊断记录", href: "/ai-diagnosis/records", icon: FileText },
      { title: "模型训练", href: "/ai-model/training", icon: Activity },
      { title: "性能分析", href: "/ai-model/performance", icon: BarChart },
      { title: "模型部署", href: "/ai-model/deployment", icon: ArrowUpDown },
    ],
  },
  {
    title: "患者管理",
    icon: Users,
    children: [
      { title: "患者列表", href: "/patients", icon: Users },
      { title: "病历管理", href: "/patients/records", icon: FileText },
      { title: "随访计划", href: "/patients/followup", icon: CalendarClock },
      { title: "患者分组", href: "/patients/groups", icon: Workflow },
    ],
  },
  {
    title: "临床决策",
    icon: Stethoscope,
    children: [
      { title: "决策支持", href: "/clinical-decision", icon: Stethoscope },
      { title: "临床路径", href: "/clinical-decision/clinical-pathways", icon: Workflow },
      { title: "诊断工具", href: "/clinical-decision/diagnostic-tools", icon: Clipboard },
      { title: "临床指南", href: "/clinical-decision/guidelines", icon: BookOpen },
      { title: "药物参考", href: "/clinical-decision/drug-reference", icon: Pill },
    ],
  },
  {
    title: "药物管理",
    icon: Pill,
    children: [{ title: "药品目录", href: "/medications", icon: Pill }],
  },
  {
    title: "健康数据",
    icon: HeartPulse,
    children: [{ title: "数据概览", href: "/health-data", icon: HeartPulse }],
  },
  {
    title: "医学研究",
    icon: Microscope,
    children: [{ title: "研究项目", href: "/research", icon: Microscope }],
  },
  {
    title: "资质验证",
    icon: Certificate,
    children: [
      { title: "资质概览", href: "/certifications", icon: Award },
      { title: "资质上传", href: "/certifications/upload", icon: FileCheck },
      { title: "验证状态", href: "/certifications/status", icon: CheckCircle },
      { title: "资质管理", href: "/certifications/management", icon: UserCheck },
      { title: "验证机构", href: "/certifications/providers", icon: ShieldCheck },
      { title: "统计分析", href: "/certifications/statistics", icon: BarChart },
    ],
  },
  {
    title: "数据安全",
    icon: Lock,
    children: [
      { title: "安全概览", href: "/security", icon: ShieldCheck },
      { title: "账户安全", href: "/security/account", icon: UserCog },
    ],
  },
  {
    title: "移动应用",
    icon: Smartphone,
    children: [{ title: "应用概览", href: "/mobile-app", icon: Smartphone }],
  },
  {
    title: "电子病历",
    icon: FileText,
    children: [{ title: "集成概览", href: "/ehr-integration", icon: Network }],
  },
  {
    title: "远程会诊",
    icon: Video,
    children: [{ title: "会诊中心", href: "/teleconsultation", icon: Video }],
  },
  {
    title: "统计分析",
    icon: BarChart3,
    children: [
      { title: "数据概览", href: "/analytics", icon: BarChart3 },
      { title: "搜索分析", href: "/search-analytics", icon: LineChart },
    ],
  },
  {
    title: "API文档",
    icon: Globe,
    children: [
      { title: "API概览", href: "/api-docs", icon: BookOpen },
      { title: "在线测试", href: "/api-docs/tester", icon: TestTube },
      { title: "使用示例", href: "/api-docs/examples", icon: Code },
      { title: "性能监控", href: "/api-docs/monitor", icon: Monitor },
      { title: "更新日志", href: "/api-docs/changelog", icon: History },
    ],
  },
  {
    title: "系统管理",
    icon: Settings,
    children: [
      { title: "管理概览", href: "/admin", icon: Settings },
      { title: "用户管理", href: "/admin/users", icon: Users },
      { title: "角色权限", href: "/admin/roles", icon: UserCog },
      { title: "系统设置", href: "/admin/settings", icon: Settings },
      { title: "系统日志", href: "/admin/logs", icon: FileText },
      { title: "数据备份", href: "/admin/backup", icon: HardDrive },
      { title: "通知管理", href: "/admin/notifications", icon: Bell },
      { title: "部署检查", href: "/admin/deployment-check", icon: AlertCircle },
      { title: "API配置", href: "/admin/api-config", icon: Key },
      { title: "API使用", href: "/admin/api-usage", icon: Activity },
      { title: "认证管理", href: "/admin/certifications", icon: Certificate },
    ],
  },
]
